# Generated by Django 4.2.2 on 2023-08-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafik_app', '0003_odberkrv_delete_odbe_rk_kv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='odberkrv',
            new_name='odberkkv',
        ),
    ]
