# Generated by Django 4.2.2 on 2023-08-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafik_app', '0004_rename_odberkrv_odberkkv'),
    ]

    operations = [
        migrations.AddField(
            model_name='odberkkv',
            name='gyarto',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='odberkkv',
            name='megnevezes',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='odberkkv',
            name='ndn',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
    ]
