# Generated by Django 4.2.2 on 2023-08-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafik_app', '0005_odberkkv_gyarto_alter_odberkkv_megnevezes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odberkkv',
            name='kategoria',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='odberkkv',
            name='rendeles',
            field=models.IntegerField(null=True),
        ),
    ]
