# Generated by Django 4.2.2 on 2023-08-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafik_app', '0006_odberkkv_kategoria_odberkkv_rendeles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odberkkv',
            name='gyarto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='odberkkv',
            name='kategoria',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='odberkkv',
            name='megnevezes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='odberkkv',
            name='ndn',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
