# Generated by Django 4.2.2 on 2023-08-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafik_app', '0007_alter_odberkkv_gyarto_alter_odberkkv_kategoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odberkkv',
            name='cikkszam',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='odberkkv',
            name='kv0',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='odberkkv',
            name='kv1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='odberkkv',
            name='kv2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='odberkkv',
            name='kv3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='odberkkv',
            name='raktarkeszlet',
            field=models.IntegerField(null=True),
        ),
    ]
